// Investment Data
export const investments = [
  {
    id: 1,
    name: "Floria Table Settings",
    industry: "Party Planning",
    founded: 2015,
    targetConsumers: "M/W in 20s",
    quarterlyRevenue: "$50,000",
    employees: 5,
    riskAssessment: "73% Return",
    askingPrice: "$100,000 for 20% equity",
    imageUrl: "/images/floria-table.jpg",
  },
  {
    id: 2,
    name: "Nathan's Hot Dogs",
    industry: "Food & Beverage",
    founded: 1998,
    targetConsumers: "Fast food lovers",
    quarterlyRevenue: "$150,000",
    employees: 25,
    riskAssessment: "85% Return",
    askingPrice: "$250,000 for 30% equity",
    imageUrl: "/images/nathans-hotdogs.jpg",
  },
  {
    id: 3,
    name: "Local Tech Helpers",
    industry: "IT Support",
    founded: 2020,
    targetConsumers: "Small Businesses & Individuals",
    quarterlyRevenue: "$45,000",
    employees: 4,
    riskAssessment: "60% Return",
    askingPrice: "$50,000 for 15% equity",
    imageUrl: "/images/localtech.jpg",
  },
  {
    id: 4,
    name: "EcoWear Handmade",
    industry: "Sustainable Fashion",
    founded: 2018,
    targetConsumers: "Eco-conscious Individuals",
    quarterlyRevenue: "$75,000",
    employees: 8,
    riskAssessment: "70% Return",
    askingPrice: "$80,000 for 25% equity",
    imageUrl: "/images/ecowear-handmade.jpg",
  },
  {
    id: 5,
    name: "FreshFarm Market",
    industry: "Organic Grocery Store",
    founded: 2016,
    targetConsumers: "Local Health Enthusiasts",
    quarterlyRevenue: "$90,000",
    employees: 10,
    riskAssessment: "65% Return",
    askingPrice: "$120,000 for 20% equity",
    imageUrl: "/images/freshfarm-market.jpg",
  },
  {
    id: 6,
    name: "AeroSnap Drones",
    industry: "Aerial Photography",
    founded: 2021,
    targetConsumers: "Events & Small Businesses",
    quarterlyRevenue: "$35,000",
    employees: 3,
    riskAssessment: "55% Return",
    askingPrice: "$40,000 for 15% equity",
    imageUrl: "/images/aerosnap.jpg",
  },
  {
    id: 7,
    name: "Sunflower Bakery",
    industry: "Bakery & Pastries",
    founded: 2019,
    targetConsumers: "Local Families & Coffee Shops",
    quarterlyRevenue: "$80,000",
    employees: 6,
    riskAssessment: "75% Return",
    askingPrice: "$90,000 for 18% equity",
    imageUrl: "/images/sunflower-bakery.jpg",
  },
  {
    id: 8,
    name: "ByteFix Repair",
    industry: "Tech Repair Services",
    founded: 2017,
    targetConsumers: "Individuals & Small Offices",
    quarterlyRevenue: "$60,000",
    employees: 7,
    riskAssessment: "68% Return",
    askingPrice: "$70,000 for 22% equity",
    imageUrl: "/images/bytefix.jpg",
  },
  {
    id: 9,
    name: "GreenScape Lawn Care",
    industry: "Landscaping Services",
    founded: 2014,
    targetConsumers: "Homeowners & Small Businesses",
    quarterlyRevenue: "$95,000",
    employees: 12,
    riskAssessment: "78% Return",
    askingPrice: "$110,000 for 25% equity",
    imageUrl: "/images/greenscape.jpg",
  },
  {
    id: 10,
    name: "Pet Haven Grooming",
    industry: "Pet Care & Grooming",
    founded: 2022,
    targetConsumers: "Pet Owners & Shelters",
    quarterlyRevenue: "$40,000",
    employees: 5,
    riskAssessment: "58% Return",
    askingPrice: "$45,000 for 15% equity",
    imageUrl: "/images/pethaven.jpg",
  }
];

// Investor Profile
export const investorProfile = {
  name: "Sabrina Arshad",
  email: "sabrina.arshad13@gmail.com",
  phone: "123-456-6789",
  linkedin: "linkedin.com/sabrina-arshad",
  maxInvestmentValue: "$50K",
  investorType: "Beginner",
  profileImage: "/images/testimonial-08.jpg"
};
